// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountRole
 */
export type AccountRole = 'player' | 'administrator';

/**
 * AccountStatus
 */
export type AccountStatus = 'active' | 'disabled' | 'deleted';

/**
 * ActionHistoryResponse
 */
export type ActionHistoryResponse = {
    /**
     * Sequence No
     */
    sequence_no: number;
    /**
     * State Version
     */
    state_version: number;
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Street
     */
    street: string;
    /**
     * Action
     */
    action: string;
    /**
     * Amount
     */
    amount: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AdminAccountListResponse
 */
export type AdminAccountListResponse = {
    /**
     * Items
     */
    items: Array<AdminAccountResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * AdminAccountResponse
 */
export type AdminAccountResponse = {
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Login Name
     */
    login_name: string;
    role: AccountRole;
    status: AccountStatus;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Avatar Text
     */
    avatar_text?: string | null;
    /**
     * Avatar Background Color
     */
    avatar_background_color?: string | null;
    /**
     * Rank Badge Theme
     */
    rank_badge_theme?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Last Login At
     */
    last_login_at?: string | null;
};

/**
 * AdminChatListResponse
 */
export type AdminChatListResponse = {
    /**
     * Items
     */
    items: Array<AdminChatResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * AdminChatResponse
 */
export type AdminChatResponse = {
    /**
     * Message Id
     */
    message_id: string;
    /**
     * Room Id
     */
    room_id: string;
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Message Type
     */
    message_type: string;
    /**
     * Content
     */
    content: string;
    /**
     * Target Account Id
     */
    target_account_id: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AdminMatchListResponse
 */
export type AdminMatchListResponse = {
    /**
     * Items
     */
    items: Array<MatchSummaryResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * AdminRoomListResponse
 */
export type AdminRoomListResponse = {
    /**
     * Items
     */
    items: Array<RoomResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * AuditLogListResponse
 */
export type AuditLogListResponse = {
    /**
     * Items
     */
    items: Array<AuditLogResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * AuditLogResponse
 */
export type AuditLogResponse = {
    /**
     * Audit Log Id
     */
    audit_log_id: string;
    /**
     * Administrator Account Id
     */
    administrator_account_id: number;
    /**
     * Action
     */
    action: string;
    /**
     * Target Account Id
     */
    target_account_id: number | null;
    /**
     * Before State
     */
    before_state: {
        [key: string]: unknown;
    } | null;
    /**
     * After State
     */
    after_state: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ChangePasswordRequest
 */
export type ChangePasswordRequest = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * CreateAccountRequest
 */
export type CreateAccountRequest = {
    /**
     * Login Name
     */
    login_name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    role?: AccountRole;
};

/**
 * CreateRoomRequest
 */
export type CreateRoomRequest = {
    /**
     * Name
     */
    name: string;
    visibility: RoomVisibility;
    /**
     * Password
     */
    password?: string | null;
    rules: RoomRules;
};

/**
 * CurrentPlayerLeaderboardStats
 */
export type CurrentPlayerLeaderboardStats = {
    /**
     * Rank
     */
    rank: number | null;
    /**
     * Rating
     */
    rating: number;
    /**
     * Highest Rating
     */
    highest_rating: number;
    /**
     * Completed Matches
     */
    completed_matches: number;
    /**
     * Diff To Previous Player
     */
    diff_to_previous_player: number | null;
    /**
     * Diff To Next Rank
     */
    diff_to_next_rank: number | null;
};

/**
 * CurrentUserResponse
 */
export type CurrentUserResponse = {
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Login Name
     */
    login_name: string;
    role: AccountRole;
    status: AccountStatus;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HandHistoryResponse
 */
export type HandHistoryResponse = {
    /**
     * Hand Id
     */
    hand_id: string;
    /**
     * Match Id
     */
    match_id: string;
    /**
     * Hand Number
     */
    hand_number: number;
    /**
     * Button Account Id
     */
    button_account_id: number;
    /**
     * Small Blind
     */
    small_blind: number;
    /**
     * Big Blind
     */
    big_blind: number;
    /**
     * Status
     */
    status: string;
    /**
     * Public Board
     */
    public_board: Array<string>;
    /**
     * Settlement Summary
     */
    settlement_summary: {
        [key: string]: unknown;
    } | null;
    /**
     * Players
     */
    players: Array<HandPlayerHistoryResponse>;
    /**
     * Actions
     */
    actions: Array<ActionHistoryResponse>;
    /**
     * Pots
     */
    pots: Array<PotHistoryResponse>;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Settled At
     */
    settled_at: string | null;
};

/**
 * HandPlayerHistoryResponse
 */
export type HandPlayerHistoryResponse = {
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Hole Cards
     */
    hole_cards: Array<string> | null;
    /**
     * Folded
     */
    folded: boolean;
    /**
     * All In
     */
    all_in: boolean;
    /**
     * Shown
     */
    shown: boolean;
    /**
     * Invested Chips
     */
    invested_chips: number;
    /**
     * Won Chips
     */
    won_chips: number;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Version
     */
    version: string;
};

/**
 * LeaderboardEntry
 */
export type LeaderboardEntry = {
    /**
     * Rank
     */
    rank: number;
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Rating
     */
    rating: number;
    /**
     * Highest Rating
     */
    highest_rating: number;
    /**
     * Completed Matches
     */
    completed_matches: number;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Avatar Text
     */
    avatar_text: string;
    /**
     * Avatar Background Color
     */
    avatar_background_color: string;
    /**
     * Rank Badge Theme
     */
    rank_badge_theme: string;
    /**
     * Win Rate
     */
    win_rate: number;
    /**
     * Last Change
     */
    last_change: number;
};

/**
 * LeaderboardResponse
 */
export type LeaderboardResponse = {
    /**
     * Batch Id
     */
    batch_id: string | null;
    /**
     * Items
     */
    items: Array<LeaderboardEntry>;
    /**
     * Total
     */
    total: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
    current_player_stats?: CurrentPlayerLeaderboardStats | null;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Login Name
     */
    login_name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Remember
     */
    remember?: boolean;
};

/**
 * MatchEndMode
 */
export type MatchEndMode = 'winner_takes_all' | 'fixed_hands';

/**
 * MatchHistoryResponse
 */
export type MatchHistoryResponse = {
    /**
     * Match Id
     */
    match_id: string;
    /**
     * Room Id
     */
    room_id: string;
    /**
     * End Mode
     */
    end_mode: string;
    /**
     * Status
     */
    status: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Void Reason
     */
    void_reason: string | null;
    /**
     * Players
     */
    players: Array<MatchPlayerHistoryResponse>;
    /**
     * Hands
     */
    hands: Array<HandHistoryResponse>;
};

/**
 * MatchListResponse
 */
export type MatchListResponse = {
    /**
     * Items
     */
    items: Array<MatchSummaryResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * MatchPlayerHistoryResponse
 */
export type MatchPlayerHistoryResponse = {
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Seat
     */
    seat: number;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Initial Chips
     */
    initial_chips: number;
    /**
     * Final Chips
     */
    final_chips: number | null;
    /**
     * Finishing Rank
     */
    finishing_rank: number | null;
    /**
     * Exit Reason
     */
    exit_reason: string | null;
};

/**
 * MatchSummaryResponse
 */
export type MatchSummaryResponse = {
    /**
     * Match Id
     */
    match_id: string;
    /**
     * Room Id
     */
    room_id: string;
    /**
     * End Mode
     */
    end_mode: string;
    /**
     * Status
     */
    status: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Void Reason
     */
    void_reason: string | null;
    /**
     * Players
     */
    players: Array<MatchPlayerHistoryResponse>;
};

/**
 * PlayerListResponse
 */
export type PlayerListResponse = {
    /**
     * Items
     */
    items: Array<PublicPlayerResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * PlayerRatingHistoryEntry
 */
export type PlayerRatingHistoryEntry = {
    /**
     * Match Id
     */
    match_id: string;
    /**
     * Before Rating
     */
    before_rating: number;
    /**
     * Delta
     */
    delta: number;
    /**
     * After Rating
     */
    after_rating: number;
    /**
     * Finishing Rank
     */
    finishing_rank: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PlayerRatingHistoryResponse
 */
export type PlayerRatingHistoryResponse = {
    /**
     * Items
     */
    items: Array<PlayerRatingHistoryEntry>;
};

/**
 * PlayerStatisticsResponse
 */
export type PlayerStatisticsResponse = {
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Reducer Version
     */
    reducer_version: number;
    /**
     * Dealt Hands
     */
    dealt_hands: number;
    /**
     * Won Hands
     */
    won_hands: number;
    /**
     * Matches Played
     */
    matches_played: number;
    /**
     * Profitable Matches
     */
    profitable_matches: number;
    /**
     * Vpip Opportunities
     */
    vpip_opportunities: number;
    /**
     * Vpip
     */
    vpip: number;
    /**
     * Vpip Rate
     */
    vpip_rate: number | null;
    /**
     * Pfr Opportunities
     */
    pfr_opportunities: number;
    /**
     * Pfr
     */
    pfr: number;
    /**
     * Pfr Rate
     */
    pfr_rate: number | null;
    /**
     * Three Bet Opportunities
     */
    three_bet_opportunities: number;
    /**
     * Three Bets
     */
    three_bets: number;
    /**
     * Three Bet Rate
     */
    three_bet_rate: number | null;
    /**
     * Showdown Opportunities
     */
    showdown_opportunities: number;
    /**
     * Showdowns
     */
    showdowns: number;
    /**
     * Showdown Wins
     */
    showdown_wins: number;
    /**
     * Showdown Rate
     */
    showdown_rate: number | null;
    /**
     * Showdown Win Rate
     */
    showdown_win_rate: number | null;
    /**
     * Decisions
     */
    decisions: number;
    /**
     * Folds
     */
    folds: number;
    /**
     * Fold Rate
     */
    fold_rate: number | null;
    /**
     * All Ins
     */
    all_ins: number;
    /**
     * Pot Total
     */
    pot_total: number;
    /**
     * Pot Count
     */
    pot_count: number;
    /**
     * Average Pot
     */
    average_pot: number | null;
    /**
     * Position Counts
     */
    position_counts: {
        [key: string]: number;
    };
};

/**
 * PotHistoryResponse
 */
export type PotHistoryResponse = {
    /**
     * Pot Number
     */
    pot_number: number;
    /**
     * Amount
     */
    amount: number;
    /**
     * Eligible Account Ids
     */
    eligible_account_ids: Array<number>;
    /**
     * Winner Payouts
     */
    winner_payouts: {
        [key: string]: number;
    };
};

/**
 * ProfileUpdateRequest
 */
export type ProfileUpdateRequest = {
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Avatar Text
     */
    avatar_text?: string | null;
    /**
     * Avatar Background Color
     */
    avatar_background_color?: string | null;
    /**
     * Rank Badge Theme
     */
    rank_badge_theme?: string | null;
};

/**
 * PublicPlayerResponse
 */
export type PublicPlayerResponse = {
    /**
     * Account Id
     */
    account_id: number;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Avatar Text
     */
    avatar_text: string;
    /**
     * Avatar Background Color
     */
    avatar_background_color: string;
    /**
     * Rank Badge Theme
     */
    rank_badge_theme: string;
    /**
     * Is Online
     */
    is_online: boolean;
};

/**
 * RatingResetResponse
 */
export type RatingResetResponse = {
    /**
     * Batch Id
     */
    batch_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Initial Rating
     */
    initial_rating: number;
    /**
     * Account Count
     */
    account_count: number;
};

/**
 * ResetPasswordRequest
 */
export type ResetPasswordRequest = {
    /**
     * Password
     */
    password: string;
};

/**
 * RoomListResponse
 */
export type RoomListResponse = {
    /**
     * Items
     */
    items: Array<RoomResponse>;
};

/**
 * RoomResponse
 */
export type RoomResponse = {
    /**
     * Room Id
     */
    room_id: string;
    /**
     * Host Account Id
     */
    host_account_id: number;
    /**
     * Name
     */
    name: string;
    visibility: RoomVisibility;
    /**
     * Has Password
     */
    has_password: boolean;
    rules: RoomRules;
    status: RoomStatus;
    /**
     * Player Count
     */
    player_count: number;
    /**
     * Spectator Count
     */
    spectator_count: number;
};

/**
 * RoomRules
 *
 * Rules that are frozen when a match starts.
 */
export type RoomRules = {
    /**
     * Max Players
     */
    max_players: number;
    end_mode: MatchEndMode;
    /**
     * Fixed Hand Count
     */
    fixed_hand_count?: number | null;
    /**
     * Starting Chips
     */
    starting_chips: number;
    /**
     * Small Blind
     */
    small_blind: number;
    /**
     * Big Blind
     */
    big_blind: number;
    /**
     * Ante
     */
    ante?: number;
    /**
     * Decision Timeout Seconds
     */
    decision_timeout_seconds?: number | null;
    /**
     * Blind Increase Every Hands
     */
    blind_increase_every_hands: number;
    /**
     * Show Remaining Board
     */
    show_remaining_board: boolean;
    /**
     * Winner May Show Hand
     */
    winner_may_show_hand: boolean;
    /**
     * Spectators Allowed
     */
    spectators_allowed: boolean;
    /**
     * Auto Start
     */
    auto_start: boolean;
    /**
     * Counted In Stats
     */
    counted_in_stats: boolean;
    /**
     * Allow Mid Match Join
     */
    allow_mid_match_join: boolean;
    /**
     * Allow Rebuys
     */
    allow_rebuys: boolean;
    /**
     * Allow Voluntary Leave
     */
    allow_voluntary_leave: boolean;
};

/**
 * RoomStatus
 */
export type RoomStatus = 'waiting' | 'active' | 'closed';

/**
 * RoomVisibility
 */
export type RoomVisibility = 'public' | 'password' | 'invite';

/**
 * UpdateAccountRequest
 */
export type UpdateAccountRequest = {
    status?: AccountStatus | null;
    role?: AccountRole | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VoidMatchRequest
 */
export type VoidMatchRequest = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * VoidMatchResponse
 */
export type VoidMatchResponse = {
    /**
     * Match Id
     */
    match_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Void Reason
     */
    void_reason: string;
};

export type LivenessApiV1HealthLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/live';
};

export type LivenessApiV1HealthLiveGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type LivenessApiV1HealthLiveGetResponse = LivenessApiV1HealthLiveGetResponses[keyof LivenessApiV1HealthLiveGetResponses];

export type ReadinessApiV1HealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready';
};

export type ReadinessApiV1HealthReadyGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type ReadinessApiV1HealthReadyGetResponse = ReadinessApiV1HealthReadyGetResponses[keyof ReadinessApiV1HealthReadyGetResponses];

export type LoginApiV1AuthLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: CurrentUserResponse;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiV1AuthLogoutPostResponse = LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type ChangePasswordApiV1MeChangePasswordPostData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/me/change-password';
};

export type ChangePasswordApiV1MeChangePasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordApiV1MeChangePasswordPostError = ChangePasswordApiV1MeChangePasswordPostErrors[keyof ChangePasswordApiV1MeChangePasswordPostErrors];

export type ChangePasswordApiV1MeChangePasswordPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ChangePasswordApiV1MeChangePasswordPostResponse = ChangePasswordApiV1MeChangePasswordPostResponses[keyof ChangePasswordApiV1MeChangePasswordPostResponses];

export type CurrentUserApiV1MeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type CurrentUserApiV1MeGetResponses = {
    /**
     * Successful Response
     */
    200: CurrentUserResponse;
};

export type CurrentUserApiV1MeGetResponse = CurrentUserApiV1MeGetResponses[keyof CurrentUserApiV1MeGetResponses];

export type ListAccountsApiV1AdminAccountsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Login Name
         */
        login_name?: string | null;
        /**
         * Role
         */
        role?: AccountRole | null;
        /**
         * Status
         */
        status?: AccountStatus | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/accounts';
};

export type ListAccountsApiV1AdminAccountsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAccountsApiV1AdminAccountsGetError = ListAccountsApiV1AdminAccountsGetErrors[keyof ListAccountsApiV1AdminAccountsGetErrors];

export type ListAccountsApiV1AdminAccountsGetResponses = {
    /**
     * Successful Response
     */
    200: AdminAccountListResponse;
};

export type ListAccountsApiV1AdminAccountsGetResponse = ListAccountsApiV1AdminAccountsGetResponses[keyof ListAccountsApiV1AdminAccountsGetResponses];

export type CreateAccountApiV1AdminAccountsPostData = {
    body: CreateAccountRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/accounts';
};

export type CreateAccountApiV1AdminAccountsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAccountApiV1AdminAccountsPostError = CreateAccountApiV1AdminAccountsPostErrors[keyof CreateAccountApiV1AdminAccountsPostErrors];

export type CreateAccountApiV1AdminAccountsPostResponses = {
    /**
     * Successful Response
     */
    201: CurrentUserResponse;
};

export type CreateAccountApiV1AdminAccountsPostResponse = CreateAccountApiV1AdminAccountsPostResponses[keyof CreateAccountApiV1AdminAccountsPostResponses];

export type UpdateAccountApiV1AdminAccountsAccountIdPatchData = {
    body: UpdateAccountRequest;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/v1/admin/accounts/{account_id}';
};

export type UpdateAccountApiV1AdminAccountsAccountIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAccountApiV1AdminAccountsAccountIdPatchError = UpdateAccountApiV1AdminAccountsAccountIdPatchErrors[keyof UpdateAccountApiV1AdminAccountsAccountIdPatchErrors];

export type UpdateAccountApiV1AdminAccountsAccountIdPatchResponses = {
    /**
     * Successful Response
     */
    200: CurrentUserResponse;
};

export type UpdateAccountApiV1AdminAccountsAccountIdPatchResponse = UpdateAccountApiV1AdminAccountsAccountIdPatchResponses[keyof UpdateAccountApiV1AdminAccountsAccountIdPatchResponses];

export type ResetPasswordApiV1AdminAccountsAccountIdResetPasswordPostData = {
    body: ResetPasswordRequest;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/v1/admin/accounts/{account_id}/reset-password';
};

export type ResetPasswordApiV1AdminAccountsAccountIdResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordApiV1AdminAccountsAccountIdResetPasswordPostError = ResetPasswordApiV1AdminAccountsAccountIdResetPasswordPostErrors[keyof ResetPasswordApiV1AdminAccountsAccountIdResetPasswordPostErrors];

export type ResetPasswordApiV1AdminAccountsAccountIdResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: CurrentUserResponse;
};

export type ResetPasswordApiV1AdminAccountsAccountIdResetPasswordPostResponse = ResetPasswordApiV1AdminAccountsAccountIdResetPasswordPostResponses[keyof ResetPasswordApiV1AdminAccountsAccountIdResetPasswordPostResponses];

export type VoidMatchApiV1AdminMatchesMatchIdVoidPostData = {
    body: VoidMatchRequest;
    path: {
        /**
         * Match Id
         */
        match_id: string;
    };
    query?: never;
    url: '/api/v1/admin/matches/{match_id}/void';
};

export type VoidMatchApiV1AdminMatchesMatchIdVoidPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VoidMatchApiV1AdminMatchesMatchIdVoidPostError = VoidMatchApiV1AdminMatchesMatchIdVoidPostErrors[keyof VoidMatchApiV1AdminMatchesMatchIdVoidPostErrors];

export type VoidMatchApiV1AdminMatchesMatchIdVoidPostResponses = {
    /**
     * Successful Response
     */
    200: VoidMatchResponse;
};

export type VoidMatchApiV1AdminMatchesMatchIdVoidPostResponse = VoidMatchApiV1AdminMatchesMatchIdVoidPostResponses[keyof VoidMatchApiV1AdminMatchesMatchIdVoidPostResponses];

export type ListAdminRoomsApiV1AdminRoomsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: RoomStatus | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/rooms';
};

export type ListAdminRoomsApiV1AdminRoomsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAdminRoomsApiV1AdminRoomsGetError = ListAdminRoomsApiV1AdminRoomsGetErrors[keyof ListAdminRoomsApiV1AdminRoomsGetErrors];

export type ListAdminRoomsApiV1AdminRoomsGetResponses = {
    /**
     * Successful Response
     */
    200: AdminRoomListResponse;
};

export type ListAdminRoomsApiV1AdminRoomsGetResponse = ListAdminRoomsApiV1AdminRoomsGetResponses[keyof ListAdminRoomsApiV1AdminRoomsGetResponses];

export type CloseRoomAdminApiV1AdminRoomsRoomIdClosePostData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/api/v1/admin/rooms/{room_id}/close';
};

export type CloseRoomAdminApiV1AdminRoomsRoomIdClosePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloseRoomAdminApiV1AdminRoomsRoomIdClosePostError = CloseRoomAdminApiV1AdminRoomsRoomIdClosePostErrors[keyof CloseRoomAdminApiV1AdminRoomsRoomIdClosePostErrors];

export type CloseRoomAdminApiV1AdminRoomsRoomIdClosePostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CloseRoomAdminApiV1AdminRoomsRoomIdClosePostResponse = CloseRoomAdminApiV1AdminRoomsRoomIdClosePostResponses[keyof CloseRoomAdminApiV1AdminRoomsRoomIdClosePostResponses];

export type ListAdminChatsApiV1AdminChatsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Room Id
         */
        room_id?: string | null;
        /**
         * Account Id
         */
        account_id?: number | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/chats';
};

export type ListAdminChatsApiV1AdminChatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAdminChatsApiV1AdminChatsGetError = ListAdminChatsApiV1AdminChatsGetErrors[keyof ListAdminChatsApiV1AdminChatsGetErrors];

export type ListAdminChatsApiV1AdminChatsGetResponses = {
    /**
     * Successful Response
     */
    200: AdminChatListResponse;
};

export type ListAdminChatsApiV1AdminChatsGetResponse = ListAdminChatsApiV1AdminChatsGetResponses[keyof ListAdminChatsApiV1AdminChatsGetResponses];

export type ListAuditLogsApiV1AdminAuditLogsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/audit-logs';
};

export type ListAuditLogsApiV1AdminAuditLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAuditLogsApiV1AdminAuditLogsGetError = ListAuditLogsApiV1AdminAuditLogsGetErrors[keyof ListAuditLogsApiV1AdminAuditLogsGetErrors];

export type ListAuditLogsApiV1AdminAuditLogsGetResponses = {
    /**
     * Successful Response
     */
    200: AuditLogListResponse;
};

export type ListAuditLogsApiV1AdminAuditLogsGetResponse = ListAuditLogsApiV1AdminAuditLogsGetResponses[keyof ListAuditLogsApiV1AdminAuditLogsGetResponses];

export type ListAdminMatchesApiV1AdminMatchesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Room Id
         */
        room_id?: string | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/matches';
};

export type ListAdminMatchesApiV1AdminMatchesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAdminMatchesApiV1AdminMatchesGetError = ListAdminMatchesApiV1AdminMatchesGetErrors[keyof ListAdminMatchesApiV1AdminMatchesGetErrors];

export type ListAdminMatchesApiV1AdminMatchesGetResponses = {
    /**
     * Successful Response
     */
    200: AdminMatchListResponse;
};

export type ListAdminMatchesApiV1AdminMatchesGetResponse = ListAdminMatchesApiV1AdminMatchesGetResponses[keyof ListAdminMatchesApiV1AdminMatchesGetResponses];

export type ListPlayersApiV1PlayersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/players';
};

export type ListPlayersApiV1PlayersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPlayersApiV1PlayersGetError = ListPlayersApiV1PlayersGetErrors[keyof ListPlayersApiV1PlayersGetErrors];

export type ListPlayersApiV1PlayersGetResponses = {
    /**
     * Successful Response
     */
    200: PlayerListResponse;
};

export type ListPlayersApiV1PlayersGetResponse = ListPlayersApiV1PlayersGetResponses[keyof ListPlayersApiV1PlayersGetResponses];

export type GetPlayerApiV1PlayersAccountIdGetData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/v1/players/{account_id}';
};

export type GetPlayerApiV1PlayersAccountIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlayerApiV1PlayersAccountIdGetError = GetPlayerApiV1PlayersAccountIdGetErrors[keyof GetPlayerApiV1PlayersAccountIdGetErrors];

export type GetPlayerApiV1PlayersAccountIdGetResponses = {
    /**
     * Successful Response
     */
    200: PublicPlayerResponse;
};

export type GetPlayerApiV1PlayersAccountIdGetResponse = GetPlayerApiV1PlayersAccountIdGetResponses[keyof GetPlayerApiV1PlayersAccountIdGetResponses];

export type UpdateMyProfileApiV1MeProfilePatchData = {
    body: ProfileUpdateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/me/profile';
};

export type UpdateMyProfileApiV1MeProfilePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMyProfileApiV1MeProfilePatchError = UpdateMyProfileApiV1MeProfilePatchErrors[keyof UpdateMyProfileApiV1MeProfilePatchErrors];

export type UpdateMyProfileApiV1MeProfilePatchResponses = {
    /**
     * Successful Response
     */
    200: PublicPlayerResponse;
};

export type UpdateMyProfileApiV1MeProfilePatchResponse = UpdateMyProfileApiV1MeProfilePatchResponses[keyof UpdateMyProfileApiV1MeProfilePatchResponses];

export type ListPlayerMatchesApiV1PlayersAccountIdMatchesGetData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/players/{account_id}/matches';
};

export type ListPlayerMatchesApiV1PlayersAccountIdMatchesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPlayerMatchesApiV1PlayersAccountIdMatchesGetError = ListPlayerMatchesApiV1PlayersAccountIdMatchesGetErrors[keyof ListPlayerMatchesApiV1PlayersAccountIdMatchesGetErrors];

export type ListPlayerMatchesApiV1PlayersAccountIdMatchesGetResponses = {
    /**
     * Successful Response
     */
    200: MatchListResponse;
};

export type ListPlayerMatchesApiV1PlayersAccountIdMatchesGetResponse = ListPlayerMatchesApiV1PlayersAccountIdMatchesGetResponses[keyof ListPlayerMatchesApiV1PlayersAccountIdMatchesGetResponses];

export type GetMatchHistoryApiV1MatchesMatchIdGetData = {
    body?: never;
    path: {
        /**
         * Match Id
         */
        match_id: string;
    };
    query?: never;
    url: '/api/v1/matches/{match_id}';
};

export type GetMatchHistoryApiV1MatchesMatchIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMatchHistoryApiV1MatchesMatchIdGetError = GetMatchHistoryApiV1MatchesMatchIdGetErrors[keyof GetMatchHistoryApiV1MatchesMatchIdGetErrors];

export type GetMatchHistoryApiV1MatchesMatchIdGetResponses = {
    /**
     * Successful Response
     */
    200: MatchHistoryResponse;
};

export type GetMatchHistoryApiV1MatchesMatchIdGetResponse = GetMatchHistoryApiV1MatchesMatchIdGetResponses[keyof GetMatchHistoryApiV1MatchesMatchIdGetResponses];

export type GetHandHistoryApiV1HandsHandIdGetData = {
    body?: never;
    path: {
        /**
         * Hand Id
         */
        hand_id: string;
    };
    query?: never;
    url: '/api/v1/hands/{hand_id}';
};

export type GetHandHistoryApiV1HandsHandIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHandHistoryApiV1HandsHandIdGetError = GetHandHistoryApiV1HandsHandIdGetErrors[keyof GetHandHistoryApiV1HandsHandIdGetErrors];

export type GetHandHistoryApiV1HandsHandIdGetResponses = {
    /**
     * Successful Response
     */
    200: HandHistoryResponse;
};

export type GetHandHistoryApiV1HandsHandIdGetResponse = GetHandHistoryApiV1HandsHandIdGetResponses[keyof GetHandHistoryApiV1HandsHandIdGetResponses];

export type LeaderboardApiV1LeaderboardGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string | null;
        /**
         * Rank Filter
         */
        rank_filter?: string | null;
        /**
         * Only With Matches
         */
        only_with_matches?: boolean;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/leaderboard';
};

export type LeaderboardApiV1LeaderboardGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LeaderboardApiV1LeaderboardGetError = LeaderboardApiV1LeaderboardGetErrors[keyof LeaderboardApiV1LeaderboardGetErrors];

export type LeaderboardApiV1LeaderboardGetResponses = {
    /**
     * Successful Response
     */
    200: LeaderboardResponse;
};

export type LeaderboardApiV1LeaderboardGetResponse = LeaderboardApiV1LeaderboardGetResponses[keyof LeaderboardApiV1LeaderboardGetResponses];

export type ResetRatingsApiV1AdminRatingResetsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/rating-resets';
};

export type ResetRatingsApiV1AdminRatingResetsPostResponses = {
    /**
     * Successful Response
     */
    201: RatingResetResponse;
};

export type ResetRatingsApiV1AdminRatingResetsPostResponse = ResetRatingsApiV1AdminRatingResetsPostResponses[keyof ResetRatingsApiV1AdminRatingResetsPostResponses];

export type GetPlayerRatingHistoryApiV1PlayersAccountIdRatingsGetData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/v1/players/{account_id}/ratings';
};

export type GetPlayerRatingHistoryApiV1PlayersAccountIdRatingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlayerRatingHistoryApiV1PlayersAccountIdRatingsGetError = GetPlayerRatingHistoryApiV1PlayersAccountIdRatingsGetErrors[keyof GetPlayerRatingHistoryApiV1PlayersAccountIdRatingsGetErrors];

export type GetPlayerRatingHistoryApiV1PlayersAccountIdRatingsGetResponses = {
    /**
     * Successful Response
     */
    200: PlayerRatingHistoryResponse;
};

export type GetPlayerRatingHistoryApiV1PlayersAccountIdRatingsGetResponse = GetPlayerRatingHistoryApiV1PlayersAccountIdRatingsGetResponses[keyof GetPlayerRatingHistoryApiV1PlayersAccountIdRatingsGetResponses];

export type ListRoomsApiV1RoomsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/rooms';
};

export type ListRoomsApiV1RoomsGetResponses = {
    /**
     * Successful Response
     */
    200: RoomListResponse;
};

export type ListRoomsApiV1RoomsGetResponse = ListRoomsApiV1RoomsGetResponses[keyof ListRoomsApiV1RoomsGetResponses];

export type CreateRoomApiV1RoomsPostData = {
    body: CreateRoomRequest;
    path?: never;
    query?: never;
    url: '/api/v1/rooms';
};

export type CreateRoomApiV1RoomsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRoomApiV1RoomsPostError = CreateRoomApiV1RoomsPostErrors[keyof CreateRoomApiV1RoomsPostErrors];

export type CreateRoomApiV1RoomsPostResponses = {
    /**
     * Successful Response
     */
    201: RoomResponse;
};

export type CreateRoomApiV1RoomsPostResponse = CreateRoomApiV1RoomsPostResponses[keyof CreateRoomApiV1RoomsPostResponses];

export type GetRoomApiV1RoomsRoomIdGetData = {
    body?: never;
    path: {
        /**
         * Room Id
         */
        room_id: string;
    };
    query?: never;
    url: '/api/v1/rooms/{room_id}';
};

export type GetRoomApiV1RoomsRoomIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRoomApiV1RoomsRoomIdGetError = GetRoomApiV1RoomsRoomIdGetErrors[keyof GetRoomApiV1RoomsRoomIdGetErrors];

export type GetRoomApiV1RoomsRoomIdGetResponses = {
    /**
     * Successful Response
     */
    200: RoomResponse;
};

export type GetRoomApiV1RoomsRoomIdGetResponse = GetRoomApiV1RoomsRoomIdGetResponses[keyof GetRoomApiV1RoomsRoomIdGetResponses];

export type GetPlayerStatisticsApiV1PlayersAccountIdStatisticsGetData = {
    body?: never;
    path: {
        /**
         * Account Id
         */
        account_id: number;
    };
    query?: never;
    url: '/api/v1/players/{account_id}/statistics';
};

export type GetPlayerStatisticsApiV1PlayersAccountIdStatisticsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPlayerStatisticsApiV1PlayersAccountIdStatisticsGetError = GetPlayerStatisticsApiV1PlayersAccountIdStatisticsGetErrors[keyof GetPlayerStatisticsApiV1PlayersAccountIdStatisticsGetErrors];

export type GetPlayerStatisticsApiV1PlayersAccountIdStatisticsGetResponses = {
    /**
     * Successful Response
     */
    200: PlayerStatisticsResponse;
};

export type GetPlayerStatisticsApiV1PlayersAccountIdStatisticsGetResponse = GetPlayerStatisticsApiV1PlayersAccountIdStatisticsGetResponses[keyof GetPlayerStatisticsApiV1PlayersAccountIdStatisticsGetResponses];
