import { z } from 'zod';

// Generated by scripts/generate-realtime-contracts.cjs. Do not edit.

export const ChatMessagePayloadSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "message_id": z.string().uuid(),
    "room_id": z.string().uuid(),
    "account_id": z.number().int(),
    "message_type": z.enum(["text","quick","custom_quick"] as const),
    "content": z.string(),
    "target_account_id": z.union([z.number().int(), z.null()]).optional(),
    "created_at": z.string().datetime({ offset: true }),
  }).passthrough();

export const ChatSendEventSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "room_id": z.string().uuid(),
    "message_type": z.enum(["text","quick","custom_quick"] as const),
    "content": z.string(),
  }).passthrough();

export const EmotePayloadSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "room_id": z.string().uuid(),
    "account_id": z.number().int(),
    "emote": z.string(),
    "target_account_id": z.union([z.number().int(), z.null()]).optional(),
  }).passthrough();

export const EmoteSendEventSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "room_id": z.string().uuid(),
    "emote": z.string(),
    "target_account_id": z.union([z.number().int(), z.null()]).optional(),
  }).passthrough();

export const GameActionEventActionTypeSchema = z.enum(["fold","check_or_call","bet_or_raise","show","muck"] as const);

export const GameActionEventSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "command_id": z.string().uuid(),
    "match_id": z.string().uuid(),
    "hand_id": z.string().uuid(),
    "state_version": z.number().int(),
    "action": z.lazy(() => GameActionEventActionTypeSchema),
    "amount": z.union([z.number().int(), z.null()]).optional(),
  }).passthrough();

export const GameActionRejectedSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "command_id": z.union([z.string().uuid(), z.null()]).optional(),
    "match_id": z.union([z.string().uuid(), z.null()]).optional(),
    "hand_id": z.union([z.string().uuid(), z.null()]).optional(),
    "state_version": z.union([z.number().int(), z.null()]).optional(),
    "error": z.string(),
  }).passthrough();

export const GameHandActionSnapshotActionTypeSchema = z.enum(["fold","check_or_call","bet_or_raise","show","muck"] as const);

export const GameHandActionSnapshotSchema = z.object({
    "sequence_no": z.number().int(),
    "state_version": z.number().int(),
    "account_id": z.number().int(),
    "street": z.string(),
    "action": z.lazy(() => GameHandActionSnapshotActionTypeSchema),
    "amount": z.union([z.number().int(), z.null()]).optional(),
  }).passthrough();

export const GameHandSettledGamePotSettlementSchema = z.object({
    "pot_number": z.number().int(),
    "amount": z.number().int(),
    "eligible_account_ids": z.array(z.number().int()),
    "winner_payouts": z.record(z.string(), z.number().int()),
  }).passthrough();

export const GameHandSettledGameShownHandSchema = z.object({
    "account_id": z.number().int(),
    "hole_cards": z.array(z.string()),
  }).passthrough();

export const GameHandSettledSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "match_id": z.string().uuid(),
    "hand_id": z.string().uuid(),
    "hand_number": z.number().int(),
    "state_version": z.number().int(),
    "account_ids": z.array(z.number().int()),
    "final_stacks": z.array(z.number().int()),
    "payoffs": z.array(z.number().int()),
    "pots": z.array(z.lazy(() => GameHandSettledGamePotSettlementSchema)).optional(),
    "shown_hands": z.array(z.lazy(() => GameHandSettledGameShownHandSchema)).optional(),
  }).passthrough();

export const GameLegalActionActionTypeSchema = z.enum(["fold","check_or_call","bet_or_raise","show","muck"] as const);

export const GameLegalActionSchema = z.object({
    "action": z.lazy(() => GameLegalActionActionTypeSchema),
    "min_amount": z.union([z.number().int(), z.null()]).optional(),
    "max_amount": z.union([z.number().int(), z.null()]).optional(),
  }).passthrough();

export const GameMatchSettledSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "match_id": z.string().uuid(),
    "state_version": z.number().int(),
    "account_ids": z.array(z.number().int()),
    "final_stacks": z.array(z.number().int()),
    "status": z.string(),
  }).passthrough();

export const GamePlayerSnapshotSchema = z.object({
    "account_id": z.number().int(),
    "seat": z.number().int(),
    "display_name": z.string(),
    "stack": z.number().int(),
    "bet": z.number().int(),
    "folded": z.boolean(),
    "all_in": z.boolean(),
    "connected": z.boolean().optional(),
  }).passthrough();

export const GamePotSettlementSchema = z.object({
    "pot_number": z.number().int(),
    "amount": z.number().int(),
    "eligible_account_ids": z.array(z.number().int()),
    "winner_payouts": z.record(z.string(), z.number().int()),
  }).passthrough();

export const GamePrivateSnapshotActionTypeSchema = z.enum(["fold","check_or_call","bet_or_raise","show","muck"] as const);

export const GamePrivateSnapshotGameHandActionSnapshotSchema = z.object({
    "sequence_no": z.number().int(),
    "state_version": z.number().int(),
    "account_id": z.number().int(),
    "street": z.string(),
    "action": z.lazy(() => GamePrivateSnapshotActionTypeSchema),
    "amount": z.union([z.number().int(), z.null()]).optional(),
  }).passthrough();

export const GamePrivateSnapshotGameLegalActionSchema = z.object({
    "action": z.lazy(() => GamePrivateSnapshotActionTypeSchema),
    "min_amount": z.union([z.number().int(), z.null()]).optional(),
    "max_amount": z.union([z.number().int(), z.null()]).optional(),
  }).passthrough();

export const GamePrivateSnapshotGamePlayerSnapshotSchema = z.object({
    "account_id": z.number().int(),
    "seat": z.number().int(),
    "display_name": z.string(),
    "stack": z.number().int(),
    "bet": z.number().int(),
    "folded": z.boolean(),
    "all_in": z.boolean(),
    "connected": z.boolean().optional(),
  }).passthrough();

export const GamePrivateSnapshotSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "match_id": z.string().uuid(),
    "hand_id": z.string().uuid(),
    "hand_number": z.number().int(),
    "state_version": z.number().int(),
    "street": z.string(),
    "button_account_id": z.number().int(),
    "actor_account_id": z.union([z.number().int(), z.null()]),
    "board": z.array(z.string()),
    "pot_amounts": z.array(z.number().int()),
    "complete": z.boolean(),
    "players": z.array(z.lazy(() => GamePrivateSnapshotGamePlayerSnapshotSchema)),
    "server_time": z.string().datetime({ offset: true }),
    "actions": z.array(z.lazy(() => GamePrivateSnapshotGameHandActionSnapshotSchema)).optional(),
    "action_deadline_at": z.union([z.string().datetime({ offset: true }), z.null()]).optional(),
    "account_id": z.number().int(),
    "hole_cards": z.array(z.string()),
    "legal_actions": z.array(z.lazy(() => GamePrivateSnapshotGameLegalActionSchema)),
  }).passthrough();

export const GamePublicSnapshotActionTypeSchema = z.enum(["fold","check_or_call","bet_or_raise","show","muck"] as const);

export const GamePublicSnapshotGameHandActionSnapshotSchema = z.object({
    "sequence_no": z.number().int(),
    "state_version": z.number().int(),
    "account_id": z.number().int(),
    "street": z.string(),
    "action": z.lazy(() => GamePublicSnapshotActionTypeSchema),
    "amount": z.union([z.number().int(), z.null()]).optional(),
  }).passthrough();

export const GamePublicSnapshotGamePlayerSnapshotSchema = z.object({
    "account_id": z.number().int(),
    "seat": z.number().int(),
    "display_name": z.string(),
    "stack": z.number().int(),
    "bet": z.number().int(),
    "folded": z.boolean(),
    "all_in": z.boolean(),
    "connected": z.boolean().optional(),
  }).passthrough();

export const GamePublicSnapshotSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "match_id": z.string().uuid(),
    "hand_id": z.string().uuid(),
    "hand_number": z.number().int(),
    "state_version": z.number().int(),
    "street": z.string(),
    "button_account_id": z.number().int(),
    "actor_account_id": z.union([z.number().int(), z.null()]),
    "board": z.array(z.string()),
    "pot_amounts": z.array(z.number().int()),
    "complete": z.boolean(),
    "players": z.array(z.lazy(() => GamePublicSnapshotGamePlayerSnapshotSchema)),
    "server_time": z.string().datetime({ offset: true }),
    "actions": z.array(z.lazy(() => GamePublicSnapshotGameHandActionSnapshotSchema)).optional(),
    "action_deadline_at": z.union([z.string().datetime({ offset: true }), z.null()]).optional(),
  }).passthrough();

export const GameRequestSnapshotEventSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "match_id": z.string().uuid(),
  }).passthrough();

export const GameShownHandSchema = z.object({
    "account_id": z.number().int(),
    "hole_cards": z.array(z.string()),
  }).passthrough();

export const LobbyRoomsUpdatedEventSchema = z.object({
    "schema_version": z.literal(1).optional(),
  }).passthrough();

export const RoomJoinEventSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "room_id": z.string().uuid(),
    "password": z.union([z.string(), z.null()]).optional(),
  }).passthrough();

export const RoomKickEventSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "room_id": z.string().uuid(),
    "target_account_id": z.number().int(),
  }).passthrough();

export const RoomKickedEventSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "room_id": z.string().uuid(),
    "reason": z.string().optional(),
  }).passthrough();

export const RoomLeaveEventSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "room_id": z.string().uuid(),
  }).passthrough();

export const RoomMemberSnapshotSchema = z.object({
    "account_id": z.number().int(),
    "ready": z.boolean(),
    "seat": z.union([z.number().int(), z.null()]).optional(),
    "connected": z.boolean().optional(),
  }).passthrough();

export const RoomReadyEventSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "room_id": z.string().uuid(),
    "ready": z.boolean(),
  }).passthrough();

export const RoomSnapshotRoomMemberSnapshotSchema = z.object({
    "account_id": z.number().int(),
    "ready": z.boolean(),
    "seat": z.union([z.number().int(), z.null()]).optional(),
    "connected": z.boolean().optional(),
  }).passthrough();

export const RoomSnapshotRoomStatusSchema = z.enum(["waiting","active","closed"] as const);

export const RoomSnapshotSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "room_id": z.string().uuid(),
    "host_account_id": z.number().int(),
    "status": z.lazy(() => RoomSnapshotRoomStatusSchema).optional(),
    "members": z.array(z.lazy(() => RoomSnapshotRoomMemberSnapshotSchema)),
    "match_id": z.union([z.string().uuid(), z.null()]).optional(),
  }).passthrough();

export const RoomStartEventSchema = z.object({
    "schema_version": z.literal(1).optional(),
    "room_id": z.string().uuid(),
  }).passthrough();

export const realtimeSchemas = {
  ChatMessagePayload: ChatMessagePayloadSchema,
  ChatSendEvent: ChatSendEventSchema,
  EmotePayload: EmotePayloadSchema,
  EmoteSendEvent: EmoteSendEventSchema,
  GameActionEvent: GameActionEventSchema,
  GameActionRejected: GameActionRejectedSchema,
  GameHandActionSnapshot: GameHandActionSnapshotSchema,
  GameHandSettled: GameHandSettledSchema,
  GameLegalAction: GameLegalActionSchema,
  GameMatchSettled: GameMatchSettledSchema,
  GamePlayerSnapshot: GamePlayerSnapshotSchema,
  GamePotSettlement: GamePotSettlementSchema,
  GamePrivateSnapshot: GamePrivateSnapshotSchema,
  GamePublicSnapshot: GamePublicSnapshotSchema,
  GameRequestSnapshotEvent: GameRequestSnapshotEventSchema,
  GameShownHand: GameShownHandSchema,
  LobbyRoomsUpdatedEvent: LobbyRoomsUpdatedEventSchema,
  RoomJoinEvent: RoomJoinEventSchema,
  RoomKickEvent: RoomKickEventSchema,
  RoomKickedEvent: RoomKickedEventSchema,
  RoomLeaveEvent: RoomLeaveEventSchema,
  RoomMemberSnapshot: RoomMemberSnapshotSchema,
  RoomReadyEvent: RoomReadyEventSchema,
  RoomSnapshot: RoomSnapshotSchema,
  RoomStartEvent: RoomStartEventSchema,
} as const;
