/* eslint-disable */
// Generated by scripts/generate-realtime-contracts.cjs. Do not edit.

export type SchemaVersion = 1;

export type CommandId = string;

export type MatchId = string;

export type HandId = string;

export type StateVersion = number;

export type ActionType = 'fold' | 'check_or_call' | 'bet_or_raise' | 'show' | 'muck';

export type Amount = number | null;


export interface GameActionEvent {
  schema_version?: SchemaVersion;
  command_id: CommandId;
  match_id: MatchId;
  hand_id: HandId;
  state_version: StateVersion;
  action: ActionType;
  amount?: Amount;
}

export type Error = string;


export interface GameActionRejected {
  schema_version?: SchemaVersion;
  command_id?: CommandId;
  match_id?: MatchId;
  hand_id?: HandId;
  state_version?: StateVersion;
  error: Error;
  [k: string]: unknown;
}

export type HandNumber = number;

export type AccountIds = number[];

export type FinalStacks = number[];

export type Payoffs = number[];


export interface GameHandSettled {
  schema_version?: SchemaVersion;
  match_id: MatchId;
  hand_id: HandId;
  hand_number: HandNumber;
  state_version: StateVersion;
  account_ids: AccountIds;
  final_stacks: FinalStacks;
  payoffs: Payoffs;
  [k: string]: unknown;
}

export type MinAmount = number | null;

export type MaxAmount = number | null;


export interface GameLegalAction {
  action: ActionType;
  min_amount?: MinAmount;
  max_amount?: MaxAmount;
  [k: string]: unknown;
}

export type Status = string;


export interface GameMatchSettled {
  schema_version?: SchemaVersion;
  match_id: MatchId;
  state_version: StateVersion;
  account_ids: AccountIds;
  final_stacks: FinalStacks;
  status: Status;
  [k: string]: unknown;
}

export type AccountId = number;

export type Seat = number;

export type DisplayName = string;

export type Stack = number;

export type Bet = number;

export type Folded = boolean;

export type AllIn = boolean;

export type Connected = boolean;


export interface GamePlayerSnapshot {
  account_id: AccountId;
  seat: Seat;
  display_name: DisplayName;
  stack: Stack;
  bet: Bet;
  folded: Folded;
  all_in: AllIn;
  connected?: Connected;
  [k: string]: unknown;
}

export type Street = string;

export type ButtonAccountId = number;

export type ActorAccountId = number | null;

export type Board = string[];

export type PotAmounts = number[];

export type Complete = boolean;

export type Players = GamePlayerSnapshot[];

export type ActionDeadlineAt = string | null;

export type AccountId1 = number;

export type HoleCards = string[];

export type LegalActions = GameLegalAction[];


export interface GamePrivateSnapshot {
  schema_version?: SchemaVersion;
  match_id: MatchId;
  hand_id: HandId;
  hand_number: HandNumber;
  state_version: StateVersion;
  street: Street;
  button_account_id: ButtonAccountId;
  actor_account_id: ActorAccountId;
  board: Board;
  pot_amounts: PotAmounts;
  complete: Complete;
  players: Players;
  action_deadline_at?: ActionDeadlineAt;
  account_id: AccountId1;
  hole_cards: HoleCards;
  legal_actions: LegalActions;
  [k: string]: unknown;
}

export interface GamePublicSnapshot {
  schema_version?: SchemaVersion;
  match_id: MatchId;
  hand_id: HandId;
  hand_number: HandNumber;
  state_version: StateVersion;
  street: Street;
  button_account_id: ButtonAccountId;
  actor_account_id: ActorAccountId;
  board: Board;
  pot_amounts: PotAmounts;
  complete: Complete;
  players: Players;
  action_deadline_at?: ActionDeadlineAt;
  [k: string]: unknown;
}

export interface GameRequestSnapshotEvent {
  schema_version?: SchemaVersion;
  match_id: MatchId;
}

export interface LobbyRoomsUpdatedEvent {
  schema_version?: SchemaVersion;
  [k: string]: unknown;
}

export type RoomId = string;

export type Password = string | null;


export interface RoomJoinEvent {
  schema_version?: SchemaVersion;
  room_id: RoomId;
  password?: Password;
}

export type Reason = string;


export interface RoomKickedEvent {
  schema_version?: SchemaVersion;
  room_id: RoomId;
  reason?: Reason;
  [k: string]: unknown;
}

export interface RoomLeaveEvent {
  schema_version?: SchemaVersion;
  room_id: RoomId;
}

export type Ready = boolean;

export interface RoomMemberSnapshot {
  account_id: AccountId;
  ready: Ready;
  seat?: Seat;
  connected?: Connected;
  [k: string]: unknown;
}

export interface RoomReadyEvent {
  schema_version?: SchemaVersion;
  room_id: RoomId;
  ready: Ready;
}

export type HostAccountId = number;

export type RoomStatus = 'waiting' | 'active' | 'closed';

export type Members = RoomMemberSnapshot[];

export interface RoomSnapshot {
  schema_version?: SchemaVersion;
  room_id: RoomId;
  host_account_id: HostAccountId;
  status?: RoomStatus;
  members: Members;
  match_id?: MatchId;
  [k: string]: unknown;
}

export interface RoomStartEvent {
  schema_version?: SchemaVersion;
  room_id: RoomId;
}

